from fpdf import FPDF
from datetime import datetime
import numpy as np

DISEASE_CLASSES = [
    'Atelectasis', 'Cardiomegaly', 'Consolidation', 'Edema', 'Effusion',
    'Emphysema', 'Fibrosis', 'Hernia', 'Infiltration', 'Mass',
    'No Finding', 'Nodule', 'Pleural Thickening', 'Pneumothorax'
]

class MediScanReport(FPDF):
    def header(self):
        self.set_font('Helvetica', 'B', 16)
        self.set_fill_color(25, 55, 109)
        self.set_text_color(255, 255, 255)
        self.cell(0, 14, '  MediScan AI — Diagnostic Report', fill=True, ln=True)
        self.set_text_color(0, 0, 0)
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, 'FOR RESEARCH AND DEMONSTRATION PURPOSES ONLY — NOT FOR CLINICAL USE', align='C')

def generate_pdf_report(mean_pred, std_pred, vitals, patient_name="Anonymous"):
    pdf = MediScanReport()
    pdf.add_page()
    
    # Patient info
    pdf.set_font('Helvetica', 'B', 12)
    pdf.set_fill_color(240, 244, 255)
    pdf.cell(0, 8, 'Patient Information', fill=True, ln=True)
    pdf.set_font('Helvetica', '', 11)
    pdf.cell(0, 7, f'Patient: {patient_name}', ln=True)
    pdf.cell(0, 7, f'Report Generated: {datetime.now().strftime("%d %B %Y, %H:%M")}', ln=True)
    pdf.cell(0, 7, f'Analysis Model: DenseNet-121 + Cross-Modal Fusion', ln=True)
    pdf.ln(4)

    # Vitals
    pdf.set_font('Helvetica', 'B', 12)
    pdf.set_fill_color(240, 244, 255)
    pdf.cell(0, 8, 'Patient Vitals', fill=True, ln=True)
    pdf.set_font('Helvetica', '', 11)
    labels = ['Temperature (°C)', 'Systolic BP (mmHg)', 'Diastolic BP (mmHg)', 'SpO2 (%)']
    for label, val in zip(labels, vitals):
        pdf.cell(90, 7, label)
        pdf.cell(0, 7, str(val), ln=True)
    pdf.ln(4)

    # Primary diagnosis
    top_idx = mean_pred.argmax()
    top_conf = mean_pred[top_idx]
    top_std = std_pred[top_idx]
    
    pdf.set_font('Helvetica', 'B', 12)
    pdf.set_fill_color(240, 244, 255)
    pdf.cell(0, 8, 'Primary Diagnosis', fill=True, ln=True)
    pdf.set_font('Helvetica', 'B', 14)
    
    if top_conf > 0.7:
        pdf.set_text_color(0, 120, 0)
    elif top_conf > 0.5:
        pdf.set_text_color(180, 100, 0)
    else:
        pdf.set_text_color(180, 0, 0)
    
    pdf.cell(0, 10, f'{DISEASE_CLASSES[top_idx]}', ln=True)
    pdf.set_text_color(0, 0, 0)
    pdf.set_font('Helvetica', '', 11)
    pdf.cell(0, 7, f'Confidence: {top_conf:.1%}  |  Uncertainty: ±{top_std:.1%}', ln=True)
    
    if top_std > 0.15:
        pdf.set_text_color(180, 0, 0)
        pdf.cell(0, 7, '⚠ High uncertainty — specialist review strongly recommended', ln=True)
        pdf.set_text_color(0, 0, 0)
    pdf.ln(4)

    # Differential diagnosis table
    pdf.set_font('Helvetica', 'B', 12)
    pdf.set_fill_color(240, 244, 255)
    pdf.cell(0, 8, 'Differential Diagnosis (Top 5)', fill=True, ln=True)
    pdf.set_font('Helvetica', 'B', 11)
    pdf.set_fill_color(25, 55, 109)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(100, 8, 'Condition', fill=True)
    pdf.cell(45, 8, 'Confidence', fill=True)
    pdf.cell(0, 8, 'Uncertainty', fill=True, ln=True)
    
    pdf.set_text_color(0, 0, 0)
    top5 = mean_pred.argsort()[-5:][::-1]
    for i, idx in enumerate(top5):
        pdf.set_fill_color(248, 250, 255) if i % 2 == 0 else pdf.set_fill_color(255, 255, 255)
        pdf.set_font('Helvetica', 'B' if i == 0 else '', 11)
        pdf.cell(100, 7, DISEASE_CLASSES[idx], fill=True)
        pdf.cell(45, 7, f'{mean_pred[idx]:.1%}', fill=True)
        pdf.cell(0, 7, f'±{std_pred[idx]:.1%}', fill=True, ln=True)
    pdf.ln(4)

    # Recommended action
    pdf.set_font('Helvetica', 'B', 12)
    pdf.set_fill_color(240, 244, 255)
    pdf.cell(0, 8, 'Recommended Next Steps', fill=True, ln=True)
    pdf.set_font('Helvetica', '', 11)
    if top_conf > 0.85:
        action = 'Confidence level is high. Initiate standard treatment protocol immediately.'
    elif top_conf > 0.65:
        action = 'Moderate confidence. Order confirmatory diagnostic tests before treatment.'
    else:
        action = 'Low confidence. Urgent specialist referral required. Do not initiate treatment.'
    pdf.multi_cell(0, 7, action)
    pdf.ln(4)

    # Disclaimer
    pdf.set_font('Helvetica', 'I', 9)
    pdf.set_text_color(150, 150, 150)
    pdf.multi_cell(0, 6,
        'DISCLAIMER: This report is generated by an AI system for research and demonstration '
        'purposes only. It must not be used for clinical diagnosis or treatment decisions. '
        'Always consult a qualified medical professional.')

    return pdf.output()
